import { create } from "zustand";

export const translations = {
  ru: {
    cart: "Корзина",
    shop: "Магазин",
    home: "Главная",
    addToCart: "В корзину",
    total: "Итого",
    order: "Оформить заказ",
    name: "Имя",
    lastName: "Фамилия",
    phone: "Телефон",
    address: "Адрес доставки",
    payment: "Способ оплаты",
    cash: "Наличными",
    transfer: "Перевод",
    sendOrder: "Заказать",
    thanks: "Спасибо за заказ!",
    empty: "Ваша корзина пуста",
    currency: "сум",
    capacity: "Объем / Емкость",
    heroTitle: "The Indian Store",
    footerDesc:
      "Аутентичная индийская косметика и товары для ухода из Индии — теперь в Узбекистане.",
    fastLinks: "Быстрые ссылки",
    info: "Информация",
    brands: "Бренды",
    about: "О нас",
    blog: "Блог",
    contacts: "Контакты",
    deliveryInfo: "Доставка и оплата",
    returns: "Возврат и обмен",
    payments: "Способы оплаты",
    faq: "Часто задаваемые вопросы",
    track: "Отследить заказ",
    policy: "Условия и политика",
    location: "Ташкент, Узбекистан",
    workHours: "Пн – Сб: 10:00 – 19:00",
    rights: "Все права защищены.",
    categoriesTitle: "Категории товаров",
    viewAll: "ПОСМОТРЕТЬ ВСЕ ТОВАРЫ",
    bestSellers: "Хиты продаж",
    features: [
      { title: "Аутентичные товары", desc: "Прямые поставки из Индии" },
      { title: "Безопасная оплата", desc: "100% защита данных" },
      { title: "Поддержка клиентов", desc: "Мы всегда готовы помочь" },
      {
        title: "Натуральность и безопасность",
        desc: "Лучшее для вас и вашей семьи",
      },
    ],
    topBar: {
      delivery: "Бесплатная доставка по Ташкенту при заказе от 500 000 сум",
      authentic: "Аутентичная индийская продукция",
      natural: "100% натурально",
    },
    aboutPage: {
      missionTitle: "Наша миссия",
      missionText:
        "В The Indian Store мы верим, что красота начинается с заботы — заботы о себе, своём благополучии и продуктах, которые вы выбираете каждый день.\n\nНаша миссия — сделать подлинную индийскую косметику и товары для здоровья доступнее для людей, которые ценят натуральные ингредиенты, проверенные временем традиции и эффективный уход за собой. Мы тщательно отбираем продукцию надёжных индийских брендов, сочетающих мудрость природы с современными стандартами качества.\n\nДля нас это больше, чем просто магазин. Мы стремимся создать пространство, где каждый сможет найти средства, помогающие чувствовать себя увереннее, комфортнее и лучше каждый день. Каждый продукт в нашем ассортименте выбран с особым вниманием и искренним желанием поддержать здоровье кожи, красоту волос и общее благополучие.\n\nСпасибо, что доверяете нам быть частью вашей заботы о себе.\n\nС любовью,\nThe Indian Store\nКрасота Природы",
      storyTitle: "Наша история",
      storyText:
        "The Indian Store был основан в 2019 году с целью сделать натуральную и подлинную индийскую косметику доступнее для людей в Узбекистане.\n\nЗа эти годы мы столкнулись со многими трудностями: пандемией COVID-19, проблемами с поставками, трансграничными ограничениями и другими испытаниями, с которыми сталкивается малый бизнес. Бывали моменты, когда магазин находился на грани закрытия.\n\nНо благодаря доверию и поддержке наших замечательных клиентов мы продолжили свой путь, развивались и продолжаем работать для вас по сей день.\n\nНаша история всё ещё пишется. Спасибо, что являетесь её частью.\n\nС любовью,\nThe Indian Store\nКрасота Природы",
    },
    features: [
      { title: "Премиальное качество", desc: "Тщательный отбор элитных брендов напрямую из Индии" },
      { title: "100% Аутентичность", desc: "Подлинные сертификаты качества и проверенные формулы" },
      { title: "Осознанный уход", desc: "Гармония древней аюрведы и современных стандартов" }
    ],
  },
  uz: {
    cart: "Savat",
    shop: "Do'kon",
    home: "Bosh sahifa",
    addToCart: "Savatga qo'shish",
    total: "Jami",
    order: "Buyurtma berish",
    name: "Ism",
    lastName: "Familiya",
    phone: "Telefon raqami",
    address: "Yetkazib berish manzili",
    payment: "To'lov usuli",
    cash: "Naqd pul",
    transfer: "Pul o'tkazmasi",
    sendOrder: "Buyurtma berish",
    thanks: "Buyurtma uchun rahmat!",
    empty: "Savat bo'sh",
    currency: "so'm",
    capacity: "Hajmi / Sig'imi",
    heroTitle: "The Indian Store",
    footerDesc:
      "Hindistondan haqiqiy ayurveda kosmetikasi va parvarishlash mahsulotlari — endi O'zbekistonda.",
    fastLinks: "Tezkor havolalar",
    info: "Ma'lumot",
    brands: "Brendlar",
    about: "Biz haqimizda",
    blog: "Blog",
    contacts: "Aloqa",
    deliveryInfo: "Yetkazib berish va to'lov",
    returns: "Qaytarish va almashtirish",
    payments: "To'lov usullari",
    faq: "Ko'p beriladigan savollar",
    track: "Buyurtmani kuzatish",
    policy: "Shartlar va qoidalar",
    location: "Toshkent, O'zbekiston",
    workHours: "Dush – Shanba: 10:00 – 19:00",
    rights: "Barcha huquqlar himoyalangan.",
    categoriesTitle: "Mahsulot toifalari",
    viewAll: "BARCHA MAHSULOTLARNI KO'RISH",
    bestSellers: "Xit mahsulotlar",
    features: [
      { title: "Asl mahsulotlar", desc: "Hindistondan to'g'ridan-to'g'ri" },
      { title: "Xavfsiz to'lov", desc: "100% ma'lumotlar himoyasi" },
      {
        title: "Mijozlarni qo'llab-quvvatlash",
        desc: "Biz har doim yordam berishga tayyormiz",
      },
      {
        title: "Tabiylik va xavfsizlik",
        desc: "Siz va oilangiz uchun eng yaxshisi",
      },
    ],
    topBar: {
      delivery:
        "500 000 so'mdan yuqori buyurtmalar uchun bepul yetkazib berish",
      authentic: "Asl hind mahsulotlari",
      natural: "100% tabiiy",
    },
    aboutPage: {
      missionTitle: "Bizning vazifamiz",
      missionText:
        "The Indian Store’da biz go‘zallik g‘amxo‘rlikdan boshlanishiga ishonamiz — o‘zingizga, sog‘lig‘ingizga va har kuni tanlaydigan mahsulotlaringizga bo‘lgan g‘amxo‘rlikdan.\n\nBizning maqsadimiz tabiiy ingredientlar, asrlar davomida sinalgan an’analar va samarali parvarishni qadrlaydigan insonlarga haqiqiy hind kosmetikasi hamda wellness mahsulotlarini taqdim etishdir.\n\nBiz tabiatning donoligini zamonaviy sifat standartlari bilan uyg‘unlashtirgan ishonchli hind brendlarining mahsulotlarini sinchkovlik bilan tanlaymiz. Biz shunchaki do‘kon emas, balki insonlar o‘zlarini yanada ishonchli, qulay va baxtli his qilishlariga yordam beradigan mahsulotlarni topishlari mumkin bo‘lgan maskan bo‘lishga intilamiz.\n\nKolleksiyamizdagi har bir mahsulot sog‘lom teri, chiroyli sochlar va umumiy farovonlikni qo‘llab-quvvatlash maqsadida mehr va mas’uliyat bilan tanlangan.\n\nO‘zingizga g‘amxo‘rlik qilish yo‘lingizda bizga ishonch bildirganingiz uchun rahmat.\n\nMuhabbat bilan,\nThe Indian Store\nTabiat Go'zalligi",
      storyTitle: "Bizning tariximiz",
      storyText:
        "The Indian Store 2019-yilda tabiiy va haqiqiy hind kosmetikasini O'zbekistondagi insonlarga yaqinroq qilish maqsadida tashkil etilgan.\n\nYo'limiz davomida ko'plab sinovlarga duch keldik: COVID davri, mahsulot yetkazib berishdagi qiyinchiliklar, chegaralar bilan bog'liq muammolar va boshqa ko'plab to'siqlar. Ba'zan do'kon faoliyatini to'xtatish haqida ham o'ylashga majbur bo'ldik.\n\nAmmo siz — aziz mijozlarimizning ishonchi va qo'llab-quvvatlashi tufayli biz davom etdik, o'sdik va bugun ham siz uchun faoliyat yuritmoqdamiz.\n\nBizning hikoyamiz hali davom etmoqda. Uning bir qismi bo'lganingiz uchun rahmat.\n\nMuhabbat bilan,\nThe Indian Store\nTabiat Go'zalligi",
    },
    features: [
      { title: "Premium sifat", desc: "Hindistondan to'g'ridan-to'g'ri elita brendlarini sinchkovlik bilan tanlash" },
      { title: "100% Asl mahsulot", desc: "Haqiqiy sifat sertifikatlari va tasdiqlangan formulalar" },
      { title: "Ongli parvarish", desc: "Qadimgi ayurveda va zamonaviy standartlar uyg'unligi" }
    ],
  },
  en: {
    cart: "Cart",
    shop: "Shop",
    home: "Home",
    addToCart: "Add to Cart",
    total: "Total",
    order: "Checkout",
    name: "First Name",
    lastName: "Last Name",
    phone: "Phone",
    address: "Delivery Address",
    payment: "Payment Method",
    cash: "Cash",
    transfer: "Transfer",
    sendOrder: "Place Order",
    thanks: "Thank you for your order!",
    empty: "Your cart is empty",
    currency: "UZS",
    capacity: "Volume / Capacity",
    heroTitle: "The Indian Store",
    footerDesc:
      "Authentic Indian cosmetics and care products from India — now in Uzbekistan.",
    fastLinks: "Quick Links",
    info: "Information",
    brands: "Brands",
    about: "About Us",
    blog: "Blog",
    contacts: "Contacts",
    deliveryInfo: "Delivery & Payment",
    returns: "Returns & Exchanges",
    payments: "Payment Methods",
    faq: "Frequently Asked Questions",
    track: "Track Order",
    policy: "Terms & Policy",
    location: "Tashkent, Uzbekistan",
    workHours: "Mon – Sat: 10:00 – 19:00",
    rights: "All rights reserved.",
    categoriesTitle: "Product Categories",
    viewAll: "VIEW ALL PRODUCTS",
    bestSellers: "Best Sellers",
    features: [
      { title: "Authentic Products", desc: "Direct from India" },
      { title: "Secure Payment", desc: "100% data protection" },
      { title: "Customer Support", desc: "Always ready to help" },
      { title: "Natural & Safe", desc: "The best for you and your family" },
    ],
    topBar: {
      delivery: "Free delivery across Tashkent for orders over 500,000 UZS",
      authentic: "Authentic Indian products",
      natural: "100% natural",
    },
    aboutPage: {
      missionTitle: "Our Mission",
      missionText:
        "At The Indian Store, we believe that beauty begins with care — care for yourself, your wellbeing, and the products you choose every day.\n\nOur mission is to bring authentic Indian cosmetics and wellness products closer to people who value natural ingredients, time-tested traditions, and effective self-care. We carefully select products from trusted Indian brands known for combining the wisdom of nature with modern quality standards.\n\nMore than a store, we strive to be a place where people can discover products that help them feel confident, comfortable, and cared for. Every item in our collection is chosen with attention, responsibility, and a genuine desire to support healthy skin, beautiful hair, and overall wellbeing.\n\nThank you for trusting us to be a part of your self-care journey.\n\nWith love,\nThe Indian Store\nBeauty of Nature",
      storyTitle: "Our Story",
      storyText:
        "The Indian Store began in 2019 with a simple idea: to bring authentic Indian beauty and wellness products closer to people who were looking for natural and effective alternatives.\n\nThe inspiration behind the store came from personal experience. Having spent many years in India, I discovered the benefits of traditional Indian cosmetics and wellness products firsthand. Their natural ingredients, time-tested formulas, and gentle approach to self-care left a lasting impression and inspired me to share them with others.\n\nWhat started as a small dream soon became a journey filled with challenges. Over the years, The Indian Store faced many obstacles — from the uncertainty of the COVID-19 pandemic to cross-border logistics issues, supply chain disruptions, and countless difficulties that small businesses often encounter. There were moments when continuing seemed almost impossible and times when closing the store felt like the only option.\n\nYet, every challenge strengthened our determination to move forward.\n\nToday, The Indian Store continues to grow thanks to the trust, support, and loyalty of our wonderful customers. What began as a passion project has become a thriving community of people who share a love for natural beauty, wellness, and mindful self-care.\n\nWe are proud of how far we have come, grateful for everyone who has been part of our journey, and excited for everything that lies ahead.\n\nThank you for growing with us and allowing us to be a part of your story.\n\nWith love,\nThe Indian Store\nBeauty of Nature",
    },
    features: [
      { title: "Premium Quality", desc: "Careful selection of elite brands direct from India" },
      { title: "100% Authenticity", desc: "Genuine quality certificates and proven formulas" },
      { title: "Mindful Care", desc: "Harmony of ancient Ayurveda and modern standards" }
    ],
  },
};

export const useLangStore = create((set) => ({
  lang: localStorage.getItem("lang") || "ru",
  t: translations[localStorage.getItem("lang") || "ru"],
  setLang: (newLang) =>
    set(() => {
      localStorage.setItem("lang", newLang);
      return { lang: newLang, t: translations[newLang] };
    }),
}));
